### ISSUE TITLE
Is pretrained model available?

### ISSUE THREAD

**Issue by BAILOOL** [DeepRNN/visual_question_answering#1]

**Comment by liu666666** [comment]
May it(https://github.com/machrisaa/tensorflow-vgg  ) help you!

**Comment by VineethRaghavan** [comment]
Yes, It is mentioned under the [results section of README.md on the homepage](https://github.com/DeepRNN/visual_question_answering#results)

[If you want, here is the direct link](https://app.box.com/s/jin3mfwnqblqiozits0xjihc1vqjvb34)
